rc -c 'echo *; echo *.c; echo [ab].c; echo ?.c; echo *.nomatch; echo d/*; echo d/*/*; echo */*.c; echo .*; echo d/../*.h'
rc -c 'echo [~a]*.c; echo [a-b].?; echo *.[ch]; echo d/*.[ch]; echo "*"; echo '"'"'*'"'"'; echo \*'
rc -c 'x=*.c; echo $x; echo $"x; y=(*.c); echo $y'
rc -c 'echo */; echo d/; echo d/sub/*'
rc -c 'echo nomatch/*; echo d/nomatch*; echo *nomatch*'
rc -c 'ls sp*'
rc -c 'echo a.c^*; echo a^*.c'
rc -c 'echo [a-c]*; echo [c-a]*; echo [a]*; echo [.]*; echo []*; echo [~]*'
rc -c '~ abc a*; echo $status; ~ abc ?b?; echo $status; ~ abc [a-c]*[c]; echo $status; ~ . .; echo $status; ~ .. .*; echo $status; ~ .x .*; echo $status; ~ / /*; echo $status; ~ a/b a?b; echo $status; ~ a/b a*b; echo $status'
rc -c '~ héllo h?llo; echo $status; ~ héllo h[é]llo; echo $status; ~ héllo h[a-z]llo; echo $status; ~ héllo h[a-ÿ]llo; echo $status; ~ x [; echo $status; ~ x [x; echo $status; ~ x [x-; echo $status'
rc -c 'x=(a b c); ~ $x a*; echo $status; ~ $x '"'"'a b c'"'"'; echo $status; ~ $x a?b?c; echo $status; ~ () ; echo $status; ~ () ""; echo $status'
rc -c '~ a; echo $status; ~ a a b; echo $status; ~ b a b; echo $status'
rc -c 'echo d/[xy].?; echo d/[xy]*; echo e/*'
rc -c 'cd d; echo *; echo ../*.c; cd sub; echo *; echo ../*'
rc -c 'echo ~/*.c' | sed "s|$WORK|WORK|g"
rc -c 'echo /nonexistent/*'
rc -c 'echo ./*.c; echo ././d/*.c'
rc -c 'echo "*.c"; echo *.c^x'
rc -c 'for(i in *.c) echo file $i'
rc -c 'case=*; ~ $case case; echo $status'
