rc -c 'echo hi >f1; cat f1; echo more >>f1; cat f1; echo again >f1; cat f1'
rc -c 'echo err >[2]f2; cat f2; echo out >[1=2]' 2>&1
rc -c 'echo x >[2=1] | wc -c'
rc -c 'cat <script.rc'
rc -c 'cat < nonexistent; echo after'
rc -c 'echo > ; echo after'
rc -c 'echo >(a b); echo after'
rc -c 'echo a >[2=]; echo b >[1=]; echo c'
rc -c 'echo hi >[9]f9; cat f9'
rc -c 'cat <>f1 | wc -c'
rc -c 'cat <> nonexistent; echo after'
rc -c 'echo abc | tr a-z A-Z'
rc -c 'cmp <{echo a} <{echo a} && echo same; cmp <{echo a} <{echo b} >/dev/null; echo st=$status'
rc -c 'echo hello >{tr a-z A-Z >/dev/null}; echo done'
rc -c 'echo one | cat >[2=1] | cat'
rc -c 'echo out; echo err >[1=2]' 2>/dev/null
rc -c 'echo out; echo err >[1=2]' 2>&1 >/dev/null
rc -c 'echo a |[2] cat'
rc -c 'echo a >[1=2] |[2] cat'
rc -c 'echo a >[1=2] |[2=0] cat'
rc -c '>f3 echo first; cat f3; >f3 {echo one; echo two}; cat f3'
rc -c '{echo a; echo b} >f4 >[2=1]; cat f4'
rc -c 'echo x >[3'
rc -c 'echo x >[a]'
rc -c 'echo x >[1=a]'
rc -c 'echo x |[1=]'
rc -c 'echo x <<[1=2] y'
rc -c 'echo x >>[1=2] y'
rc -c 'echo x > f5 > f6; ls f5 f6'
rc -c 'echo x >f7 >f8; cat f7 f8 | wc -c'
rc -c 'cat < /dev/null <script.rc'
rc -c 'echo ok > "; ls'
rc -c 'x=f10; echo hi >$x; cat f10'
rc -c 'echo hi >*.c; echo st=$status; ls'
rc -c 'echo hi >a.c; echo x >a.[c]; cat a.c'
